/**
 * The style shelf.
 *
 * Ink colours are taken from real Risograph drums and real process inks, which
 * is why they look right and why they overprint into sensible third colours.
 *
 * `detail` describes what the Detail slider drives for this style: which
 * engine option it maps to, and the range it sweeps. Sliders run 0-1 and get
 * mapped here, so one control means something sensible everywhere.
 */

export const PRESETS = [
  {
    id: 'riso-pink',
    label: 'Riso Pink',
    hint: 'Two drums, slightly out of register',
    engine: 'riso',
    paper: '#f3ede0',
    inks: ['#ff48b0', '#0078bf'],
    sep: 'tone',
    params: { grain: 0.55, offset: 2.6, spread: 0.62, maxInk: 0.94 },
    detail: { key: 'offset', min: 0, max: 8, value: 0.33, label: 'Registration' },
    tone: { exposure: 0.05, contrast: 0.14, warmth: 0 },
    finish: { grain: 0.30, fibre: 0.55, vignette: 0.10 },
  },
  {
    id: 'riso-sun',
    label: 'Riso Sun',
    hint: 'Orange and burgundy on cream',
    engine: 'riso',
    paper: '#f6efdc',
    inks: ['#ff8f1c', '#8e2f5a'],
    sep: 'tone',
    params: { grain: 0.62, offset: 2.2, spread: 0.66, maxInk: 0.92 },
    detail: { key: 'offset', min: 0, max: 8, value: 0.28, label: 'Registration' },
    tone: { exposure: 0.06, contrast: 0.16, warmth: 0.15 },
    finish: { grain: 0.32, fibre: 0.6, vignette: 0.12 },
  },
  {
    id: 'riso-forest',
    label: 'Riso Forest',
    hint: 'Green, teal and black, three passes',
    engine: 'riso',
    paper: '#efeee4',
    inks: ['#ffd400', '#00a95c', '#1b2a35'],
    sep: 'colour',
    params: { grain: 0.5, offset: 1.9, maxInk: 0.9 },
    detail: { key: 'offset', min: 0, max: 7, value: 0.26, label: 'Registration' },
    tone: { exposure: 0.04, contrast: 0.12, warmth: -0.05 },
    finish: { grain: 0.28, fibre: 0.5, vignette: 0.1 },
  },
  {
    id: 'newsprint',
    label: 'Newsprint',
    hint: 'One black screen on cheap stock',
    engine: 'halftone',
    paper: '#e5e2d8',
    inks: ['#1a1a1a'],
    sep: 'tone',
    params: { cell: 6, angle: 45, shape: 'dot', spread: 0.95, maxInk: 1 },
    detail: { key: 'cell', min: 2.4, max: 16, value: 0.30, label: 'Dot size' },
    tone: { exposure: 0.08, contrast: 0.22, warmth: 0.04 },
    finish: { grain: 0.22, fibre: 0.7, vignette: 0.14 },
  },
  {
    id: 'process',
    label: 'Process Colour',
    hint: 'Full CMYK rosette, like a magazine',
    engine: 'halftone',
    paper: '#faf7f0',
    inks: ['#00aeef', '#ec008c', '#fff200', '#231f20'],
    sep: 'colour',
    params: { cell: 5, angle: 15, shape: 'dot', maxInk: 0.95 },
    detail: { key: 'cell', min: 2.2, max: 14, value: 0.24, label: 'Dot size' },
    tone: { exposure: 0.03, contrast: 0.10, warmth: 0 },
    finish: { grain: 0.16, fibre: 0.35, vignette: 0.08 },
  },
  {
    id: 'duotone-dusk',
    label: 'Dusk',
    hint: 'Smooth two-colour gradient, no screen',
    engine: 'duotone',
    paper: '#f2eee9',
    inks: ['#f0567a', '#2a3a72'],
    sep: 'tone',
    params: { spread: 0.72, maxInk: 0.97 },
    detail: { key: 'spread', min: 0.35, max: 1, value: 0.55, label: 'Blend' },
    tone: { exposure: 0.05, contrast: 0.18, warmth: 0 },
    finish: { grain: 0.20, fibre: 0.4, vignette: 0.16 },
  },
  {
    id: 'cyanotype',
    label: 'Cyanotype',
    hint: 'Sun-printed on brushed emulsion',
    engine: 'sunprint',
    paper: '#efe9d8',
    inks: ['#0e3f6b'],
    sep: 'tone',
    params: { bloom: 0.45, wash: true },
    detail: { key: 'bloom', min: 0, max: 1.2, value: 0.38, label: 'Exposure' },
    tone: { exposure: 0.02, contrast: 0.2, warmth: 0 },
    finish: { grain: 0.24, fibre: 0.75, vignette: 0.2 },
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    hint: 'White lines burned onto blue',
    engine: 'contour',
    paper: '#173a63',
    inks: ['#8fb8de', '#ffffff'],
    blend: 'screen',
    sep: 'tone',
    params: { levels: 10, lineWidth: 1, fill: 0.16 },
    detail: { key: 'levels', min: 4, max: 22, value: 0.35, label: 'Contours' },
    tone: { exposure: 0.02, contrast: 0.24, warmth: 0 },
    finish: { grain: 0.18, fibre: 0.4, vignette: 0.22 },
  },
  {
    id: 'topographic',
    label: 'Topographic',
    hint: 'Height lines, like a survey map',
    engine: 'contour',
    paper: '#f4efe3',
    inks: ['#c96a3f', '#3d2f26'],
    sep: 'tone',
    params: { levels: 12, lineWidth: 1, fill: 0.34 },
    detail: { key: 'levels', min: 4, max: 26, value: 0.36, label: 'Contours' },
    tone: { exposure: 0.04, contrast: 0.2, warmth: 0.08 },
    finish: { grain: 0.20, fibre: 0.6, vignette: 0.12 },
  },
  {
    id: 'screenprint',
    label: 'Screenprint',
    hint: 'Flat blocks, pulled by hand',
    engine: 'screenprint',
    paper: '#f0ebdd',
    inks: ['#f2b705', '#e2483d', '#22303f'],
    sep: 'tone',
    params: { levels: 3, wobble: 0.6, spread: 0.7, maxInk: 0.95 },
    detail: { key: 'levels', min: 2, max: 7, value: 0.2, label: 'Steps' },
    tone: { exposure: 0.05, contrast: 0.26, warmth: 0.05 },
    finish: { grain: 0.22, fibre: 0.5, vignette: 0.1 },
  },
  {
    id: 'engraving',
    label: 'Engraving',
    hint: 'Crosshatched by a very patient hand',
    engine: 'hatch',
    paper: '#f1ead9',
    inks: ['#241f1c'],
    sep: 'tone',
    params: { spacing: 6, lineWidth: 1.4, passes: 4 },
    detail: { key: 'spacing', min: 3, max: 16, value: 0.28, label: 'Line gap' },
    tone: { exposure: 0.05, contrast: 0.3, warmth: 0.05 },
    finish: { grain: 0.20, fibre: 0.65, vignette: 0.14 },
  },
  {
    id: 'bayer',
    label: 'Ordered Dither',
    hint: 'Hard 8x8 grid, pure and mechanical',
    engine: 'dither',
    paper: '#f7f4ec',
    inks: ['#1b1b1b'],
    params: { cell: 1, strength: 1 },
    detail: { key: 'cell', min: 1, max: 5, value: 0, label: 'Pixel size' },
    tone: { exposure: 0.05, contrast: 0.2, warmth: 0 },
    finish: { grain: 0.10, fibre: 0.35, vignette: 0.1 },
  },
  {
    id: 'handheld',
    label: 'Handheld',
    hint: 'Four shades of green, 1989',
    engine: 'dither',
    paper: '#9bbc0f',
    inks: ['#8bac0f', '#306230', '#0f380f'],
    params: { cell: 2, strength: 0.9 },
    detail: { key: 'cell', min: 1, max: 6, value: 0.2, label: 'Pixel size' },
    tone: { exposure: 0.08, contrast: 0.22, warmth: 0 },
    finish: { grain: 0.06, fibre: 0.2, vignette: 0.12 },
  },
  {
    id: 'diffusion',
    label: 'Diffusion',
    hint: 'Error-diffused, soft and cloudy',
    engine: 'diffuse',
    paper: '#f4f1e8',
    inks: ['#c2352f', '#1f3d7a'],
    params: { strength: 1 },
    detail: { key: 'strength', min: 0.4, max: 1, value: 0.8, label: 'Spread' },
    tone: { exposure: 0.04, contrast: 0.14, warmth: 0 },
    finish: { grain: 0.12, fibre: 0.4, vignette: 0.1 },
  },
  {
    id: 'terminal',
    label: 'Terminal',
    hint: 'Every pixel is a character',
    engine: 'ascii',
    paper: '#0d1412',
    inks: ['#5bf29a'],
    blend: 'screen',
    sep: 'tone',
    params: { cell: 9 },
    detail: { key: 'cell', min: 5, max: 22, value: 0.24, label: 'Type size' },
    tone: { exposure: 0.06, contrast: 0.26, warmth: 0 },
    finish: { grain: 0.10, fibre: 0.15, vignette: 0.3 },
  },
  {
    id: 'typewriter',
    label: 'Typewriter',
    hint: 'Struck onto a sheet of copy paper',
    engine: 'ascii',
    paper: '#f2ece0',
    inks: ['#2b2723'],
    sep: 'tone',
    params: { cell: 10 },
    detail: { key: 'cell', min: 5, max: 24, value: 0.26, label: 'Type size' },
    tone: { exposure: 0.06, contrast: 0.24, warmth: 0.06 },
    finish: { grain: 0.20, fibre: 0.7, vignette: 0.12 },
  },
];

export const PRESET_BY_ID = Object.fromEntries(PRESETS.map((p) => [p.id, p]));

/** Map the 0-1 Detail slider onto whatever this style's detail control is. */
export function detailValue(preset, t) {
  const d = preset.detail;
  if (!d) return null;
  return { key: d.key, value: d.min + (d.max - d.min) * t };
}
